### PR TITLE
Add 'lodash-compat' into the check list

### PR DESCRIPTION
**Pull request by AlexKVal**
Inspired by https://github.com/react-bootstrap/react-bootstrap/pull/1341
thnx @dmatteo :cherries: 

/cc @react-bootstrap/collaborators

### CODE REVIEW

**Comment by dmatteo** [comment]
:+1:

**Comment by mtscout6** [comment]
:shipit:

**Comment by AlexKVal** [comment]
`0.1.4` published.

**Comment by dmatteo** [comment]
\o/

**Pull request merged**
